### ISSUE TITLE
ID and MTSCREATE not returned for active positions?

### ISSUE THREAD

**Issue by hems** [bitfinexcom/bfx-api-node-rest#14]
I would like to track open positions and link them to positions in the history once they're closed.

The problem I found is that positions don't have a unique `ID` or `MTSCREATE` field while they're active, so it's "less than easy" to keep track of a position considering the application might go offline in between syncs.

Having an ID or MTSCREATE for open positions would make it easier to link an "open position" to a "position in history" once it's closed.

>TLDR: Can we add ID and MTSCREATE to the `/v2/auth/r/positions` endpoint ?

**Comment by f3rno** [comment]
I'm closing as this is a dup of #15
