### ISSUE TITLE
mapping delisted symbols

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bfx-api-node-rest#19]
Using the bitfinex reports website I can see my old (pre fork) tBCHUSD trades, and they get mapped on the UI to BCH/USD in the same way that tBABUSD trades are.  Where can I find this mapping?

**Comment by f3rno** [comment]
Currently there is no way to query the mapping via the API, and we have no plans to implement it. This may be implemented in the future, if so I will re-open this issue and update it.
