### ISSUE TITLE
/r/trades/tBTCUSD/hist documentation is wrong

### ISSUE THREAD

**Issue by hems** [bitfinexcom/bfx-api-node-rest#31]
The documentation on https://docs.bitfinex.com/v2/reference#rest-auth-trades-hist describes the return was:

![image](https://user-images.githubusercontent.com/27327/60914547-097ec400-a28a-11e9-9927-924838551492.png)

But when querying using the API the result is actually is an array with 4 values which i believe are:

[orderId, timestamp, amount, price]

here is a sample:

````
[ 374853368, 1562249641769, -0.xx, 11850 ]
[ 374853367, 1562249639715, -0.xxx, 11850 ]
[ 374853366, 1562249638931, -0.xxx, 11850 ]
[ 374853365, 1562249634112, 0.xx, 11851 ]
[ 374853364, 1562249632115, -0.xxx, 11850 ]
[ 374853363, 1562249632084, -0.xxx, 11850 ]
[ 374853362, 1562249626753, -0.xxx, 11850 ]
[ 374853361, 1562249625874, -0.xxx, 11850 ]
````

Would be great to differenciate

**Comment by f3rno** [comment]
This has been fixed on the backend
