### ISSUE TITLE
get deposit address via v2 API

### ISSUE THREAD

**Issue by gasolin** [bitfinexcom/bfx-api-node-rest#34]
https://github.com/bitfinexcom/bfx-api-node-rest/blob/master/lib/rest1.js#L450

passing params method: 'tetheruss', 'wallet': 'exchange', op_renew: 0 with new API /v2/auth/w/deposit/address not work for all methods

**Comment by JacobPlaster** [comment]
Could you please provide the response for us to debug with?

**Comment by f3rno** [comment]
@JacobPlaster close due to inactivity and lack of detail.

**Comment by gasolin** [comment]
issue fixed from the API server side
