### ISSUE TITLE
can not withdraw LTC via API REST2

### ISSUE THREAD

**Issue by rozsada** [bitfinexcom/bfx-api-node-rest#41]
#### Issue type
- [ x ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I can not withdraw LTC via API REST2. Only LTC!
I can withdraw EOS with the same code but can not LTC.

#### Steps to reproduce
-

##### Additional Notes:
-my code:
    const BFX = require('bitfinex-api-node');
    const bfx = new BFX({apiKey: apiKey, apiSecret: apiSecret, transform: true});
    // REST:
    const rest = bfx.rest(2, { transform: true });
    //const rest = bfx.rest(1 );
    let address = ''
    let method = ''
    if (coin == 'EOS') {
      method = 'eos'
      address = config.EOS.address
    }
    if (coin == 'LTC') {
      method = 'litecoin'
      address = config.LTC.address
    }
   
      rest.withdraw({
        wallet: 'exchange', // v1: walletselected: 'exchange'
        method: method, // v1: withdraw_type: coin.toLowerCase()
        amount: amount.toString(), // v1: amount.toString()
        address: address
      })
        .then((res) => {
          console.log(`\nwithdraw confirmed:`)
          console.log(res)
        })

result:

withdraw confirmed:
[ 0,
  null,
  'litecoin',
  null,
  'exchange',
  0.81457456,
  null,
  null,
  0.001 ]
result seems to be successful, but fund is not transfered

And extra note: 'amount' must be a String not a Number as is suggested.

**Comment by rozsada** [comment]
There is still no answer! I ask you to fix the bug!
Thanks

**Comment by JacobPlaster** [comment]
Hi @rozsada, thanks for opening an issue. I think that the withdrawal is failing for a valid reason here but due to this line (https://github.com/bitfinexcom/bfx-api-node-rest/blob/f17fd2e79949ca7c20a3f7f30f4528158e8ee13e/lib/rest2.js#L1244) the actual error message is being filtered out. This needs to be fixed but may require a major version bump.

For debug purposes could you try replacing the function with this:

```
return this._makeAuthRequest('/auth/w/withdraw', params, cb)
      .then(console.log)
```

And paste the output here? Thanks

**Comment by rozsada** [comment]
Do you remember that EOS withdrawal is ok?
As for me, a bug is hidden directly in the LTC params/description.
Anyway I try.
Thanks

**Comment by JacobPlaster** [comment]
Any update on this @rozsada?

**Comment by rozsada** [comment]
Hi,
I have tried:
here is the log:
[ 1572938166443,
  'acc_wd-req',
  null,
  null,
  [ 0,
    null,
    'litecoin',
    null,
    'exchange',
    0.48004592,
    null,
    null,
    0.001 ],
  null,
  'SUCCESS',
  'Cannot withdraw 0.48104592 LTC from your exchange wallet. The available balance is only 0.48004592 LTC. If you have limit orders, open positions, unused or active margin funding, this will decrease your available balance. To increase it, you can cancel limit orders or reduce/close your positions.' ]


04 листопада 2019, 13:48:35, від "Jacob Plaster" <notifications@github.com>:

Any update on this @rozsada?

**Comment by rozsada** [comment]
fee is added not subtracted to the avail.balance. 

04 листопада 2019, 13:48:35, від "Jacob Plaster" <notifications@github.com>:

Any update on this @rozsada?

**Comment by rozsada** [comment]
It works when minus the fee:
[ 1572939680251,
  'acc_wd-req',
  null,
  null,
  [ 13248017,
    null,
    'litecoin',
    null,
    'exchange',
    0.47904592,
    null,
    null,
    0.001 ],
  null,
  'SUCCESS',
  'Your withdrawal request has been successfully submitted.' ]

That is why it worked with EOS, there is no fee there.
Thanks
 

04 листопада 2019, 13:48:35, від "Jacob Plaster" <notifications@github.com>:

Any update on this @rozsada?

**Comment by JacobPlaster** [comment]
Ok glad the problem Is solved. I will open a PR to update the lib so the error response is returned.
