### ISSUE TITLE
transfer api called the wrong endpoint

### ISSUE THREAD

**Issue by gasolin** [bitfinexcom/bfx-api-node-rest#45]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description

The transfer API called the wrong `/auth/w/funding/auto` endpoint
https://github.com/bitfinexcom/bfx-api-node-rest/blob/master/lib/rest2.js#L1240

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by gasolin** [comment]
FYR from the user report

```
I am trying to transfer BTC between my exchange and margin wallets using the offical node library and am recieving the following error: StatusCodeError: 500 - ["error",10001,"This currency cannot be used in margin funding"] Here is the code to reproduce the error: await this.rest.transfer({ from: "exchange", to: "margin", amount: 0.001, currency: "btc" });
```

**Comment by gasolin** [comment]
right API should be `/v2/auth/w/transfer`

**Comment by JacobPlaster** [comment]
Thanks for finding that issue @gasolin, much appreciated!

**Comment by JacobPlaster** [comment]
Fixed in https://github.com/bitfinexcom/bfx-api-node-rest/pull/46

**Comment by JacobPlaster** [comment]
Published to NPM https://www.npmjs.com/package/bfx-api-node-rest version `2.0.6`
