### ISSUE TITLE
Getting server error (500) code: 10001 message: "action: disabled" when submiting order

### ISSUE THREAD

**Issue by bl4ze** [bitfinexcom/bfx-api-node-rest#52]
#### Issue type
- [X ] bug

#### Brief description
I am using RESTv2 and trying to submit new EXCHANGE STOP LIMIT order.
#### Steps to reproduce
```
const { RESTv2 } = require('bfx-api-node-rest')
const { Order } = require('bfx-api-node-models')
***some code ommited***
const api = new RESTv2({apiKey: key.key, apiSecret: encr.decrypt(key.secret)})
const orderData = {
            symbol,
            amount: orderAmount,
            price,
            priceAuxLimit: stopPrice,
            type: 'EXCHANGE STOP LIMIT'
        }

const order = new Order({data: orderData})
const result = await api.submitOrder(order)
```
##### Additional Notes:
Am I doing something wrong? Can you give me a hint?

**Comment by JacobPlaster** [comment]
Hey @bl4ze try this instead

```
// Build new order
const o = new Order({
  cid: Date.now(),
  symbol,
  price,
  priceAuxLimit: stopPrice,
  amount: 0.001,
  type: 'EXCHANGE STOP LIMIT',
}, api)

o.submit().then(() => {
  debug(
    'got submit confirmation for order %d [%d] [tif: %d]',
    o.cid, o.id, o.mtsTIF
  )
})
  .catch((err) => console.log(err))
```

Example take from here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/rest2/submit_order.js

**Comment by bl4ze** [comment]
Hey @JacobPlaster, thanks for the help.
The order was submitted successfully.
However it is was placed as EXCHANGE LIMIT, instead of EXCHANGE STOP LIMIT.
Do you have any idea on this issue?

Here is the code I used:
```
const order = new Order({
            cid: Date.now(),
            symbol,
            price,
            priceAuxLimit: stopPrice,
            amount: orderAmount,
            type: 'EXCHANGE STOP LIMIT',
          }, this.api)
  const result = await order.submit()
```

**Comment by bl4ze** [comment]
It was the nature of the order. Stop limit sell should be below market price. It's working properly now.

**Comment by Savic** [comment]
Hello, I am getting quiet the similar response from the server.

I did not want to open up a new issue, therefore placing a question here.

I am using a **paper-trading Sub-Account** in order to test my SW using the following code snippet:

`        const o = new Order({
            cid: Date.now(),
            symbol: "tTESTBTC/TESTUSD",
            amount: "0.001",
            type: 'EXCHANGE MARKET',
        }, rest2);

        o.submit().then(() => {
            console.log(
                'got submit confirmation for order %d [%d] [tif: %d]',
                o.cid, o.id, o.mtsTIF
            );
        }) .catch((err) => console.error(err))
`

The error response is:

name = "StatusCodeError"
statusCode = 500
message = "500 - [\"error\",10001,\"action: disabled\"]"
error = [
  "error",
  10001,
  "action: disabled"
]


Is the given request-form correct?

Any advice or help is much appreciated!

K. R.,
Savic

**Comment by Savic** [comment]
> Hello, I am getting quiet the similar response from the server.
> 
> I did not want to open up a new issue, therefore placing a question here.
> 
> I am using a **paper-trading Sub-Account** in order to test my SW using the following code snippet:
> 
> ```
> const o = new Order({
>             cid: Date.now(),
>             symbol: "tTESTBTC/TESTUSD",
>             amount: "0.001",
>             type: 'EXCHANGE MARKET',
>         }, rest2);
> 
>         o.submit().then(() => {
>             console.log(
>                 'got submit confirmation for order %d [%d] [tif: %d]',
>                 o.cid, o.id, o.mtsTIF
>             );
>         }) .catch((err) => console.error(err))
> ```
> 
> The error response is:
> 
> name = "StatusCodeError"
> statusCode = 500
> message = "500 - ["error",10001,"action: disabled"]"
> error = [
> "error",
> 10001,
> "action: disabled"
> ]
> 
> Is the given request-form correct?
> 
> Any advice or help is much appreciated!
> 
> K. R.,
> Savic
> 
> Edit:
> 
> The trading symbol was invalid "tTESTBTC:TESTUSD"

**Comment by mnsr94** [comment]
Other fixes for the error "action: disabled" is making sure you put the instrument identifier exactly as shown on the website. What went wrong for me is I used the symbol "FILF0:USTF0" instead of "tFILF0:USTF0".
